### ISSUE TITLE
Steps to install it

### ISSUE THREAD

**Issue by julian-rare** [jasonnathan/meteor-react-router-ssr#1]
Is there a command like 

meteor add jasonnathan:meteor-react-router-ssr

or how is it done?

**Comment by pipewrk** [comment]
Hey @julian-rare sorry for [the mix-up](https://github.com/thereactivestack-legacy/meteor-react-router-ssr/issues/101#issuecomment-265912914). You will need to create a local packages directory in your app root, then clone this repo and do a simple add as usual

````
mkdir packages
git clone https://github.com/jasonnathan/meteor-react-router-ssr packages/meteor-react-router-ssr
meteor add jasonnathan:react-router-ssr
````

I'll see if I can push this up to atmosphere
***Edit**
I published this to [atmosphere](https://atmospherejs.com/jasonnathan/react-router-ssr)
Now you can simply `meteor add jasonnathan:react-router-ssr`

***Tip**
You can do this for all meteor packages too - in case you need to modify someone's package. You'd need to update the `package.js` and `package.json` in your own clone if you choose to do so.

**Comment by julian-rare** [comment]
awesome! thank you!

**Comment by pipewrk** [comment]
Okay to close this?

**Comment by julian-rare** [comment]
please
